language: ruby
rvm:
- 2.5.0

env:
    -AWS_USER_ID="379212824536" AWS_ECR_APP="379212824536.dkr.ecr.us-east-1.amazonaws.com/backend-g25"

services:
    - docker
branches:
    - only:
        - development
        - main
        - travis-conf
install:
    - docker-compose build 
    
script:
    - docker-compose up -d
    - docker-compose run app rspec --format documentation spec/requests/user_request_spec.rb
    #- sed -i -e 's/\r$/\n/' start.sh
    #- sed -i -e 's/\r$/\n/' stop.sh
    #- sed -i -e 's/\r$/\n/' install.sh
    #- docker-compose exec app bundle exec db:create
    #- docker-compose exec app bundle exec db:schema:load
    #- docker-compose exec app bundle exec rspec
    - zip -r latest *
    - mkdir -p dpl_cd_upload
    - mv latest.zip dpl_cd_upload/latest.zip

after_success:
    - docker --version
    - pip install --user awscli #instala el cliente de aws
#    - export PATH=$PATH:$HOME/.local/bin # pone aws en el path 
#    - eval $(aws ecr get-login --region sa-east-1 --no-include-email) #necesita AWS_ACCESS_KEY_ID y AWS_SECRET_ACCESS_KEY envars
#    - docker build -t $AWS_ECR_APP:latest api
#    - docker tag $AWS_ECR_APP:latest
#    - docker push $AWS_ECR_APP:latest
#    - docker images
#deploy:
#    -provider: s3
#     access_key_id: $AWS_ACCESS_KEY_ID
#     secret_access_key: $AWS_SECRET_ACCESS_KEY
#     local_dir: dpl_cd_upload
#     skip_cleanup: true 
#     bucket: "s3-docker-images"
#     region: us-east-1
#     upload-dir: latest
#     provider: codedeploy
#     access_key_id: $AWS_ACCESS_KEY_ID
#     secret_access_key: $AWS_SECRET_ACCESS_KEY
#     bucket: "s3-docker-images"
#     key: latest/latest.zip
#     bundle_type: zip
#     application: backend-g25
#     deployment_group: backned-g25-staging
#     region: us-east-1
#     wait_until_deployed: true
#     on:
#        branch: master